# <center> Bài tập Thực hành môn Khai phá Dữ liệu </center>

### **Họ và tên:** Huỳnh Nguyễn Thế Dân
### **MSSV:** 21110256
### **Lớp:** 21TTH1

##  1. Khoảng cách giữa các điểm trong dữ liệu số

In [18]:
import pandas as pd
import numpy as np

df = pd.read_csv('ionosphere\\ionosphere.data', header= None)

display(df.head())
df.info()

0   1        2        3        4        5        6        7        8   \
0   1   0  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.00000   
1   1   0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
2   1   0  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
3   1   0  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
4   1   0  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   

        9   ...       25       26       27       28       29       30  \
0  0.03760  ... -0.51171  0.41078 -0.46168  0.21266 -0.34090  0.42267   
1 -0.04549  ... -0.26569 -0.20468 -0.18401 -0.19040 -0.11593 -0.16626   
2  0.01198  ... -0.40220  0.58984 -0.22145  0.43100 -0.17365  0.60436   
3  0.00000  ...  0.90695  0.51613  1.00000  1.00000 -0.20099  0.25682   
4 -0.16399  ... -0.65158  0.13290 -0.53206  0.02431 -0.62197 -0.05707   

        31       32       33  34  
0 -0.54487  0.18641 -0.45300   g  
1 -0.06288 -0.13738 -0.02447   b  
2 -0.24180  0.56045 -0.38238   g  
3  1.00000 -0.32382  1.00000   b  
4 -0.59573 -0.04608 -0.65697   g  

[5 rows x 35 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 35 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       351 non-null    int64  
 1   1       351 non-null    int64  
 2   2       351 non-null    float64
 3   3       351 non-null    float64
 4   4       351 non-null    float64
 5   5       351 non-null    float64
 6   6       351 non-null    float64
 7   7       351 non-null    float64
 8   8       351 non-null    float64
 9   9       351 non-null    float64
 10  10      351 non-null    float64
 11  11      351 non-null    float64
 12  12      351 non-null    float64
 13  13      351 non-null    float64
 14  14      351 non-null    float64
 15  15      351 non-null    float64
 16  16      351 non-null    float64
 17  17      351 non-null    float64
 18  18      351 non-null    float64
 19  19      351 non-null    float64
 20  20      351 non-null    float64
 21  21      351 non-null    float64
 22  22

In [19]:
df.pop(df.columns[34])

0      g
1      b
2      g
3      b
4      g
      ..
346    g
347    g
348    g
349    g
350    g
Name: 34, Length: 351, dtype: object

In [20]:
display(df)

0   1        2        3        4        5        6        7        8   \
0     1   0  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.00000   
1     1   0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
2     1   0  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
3     1   0  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
4     1   0  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   
..   ..  ..      ...      ...      ...      ...      ...      ...      ...   
346   1   0  0.83508  0.08298  0.73739 -0.14706  0.84349 -0.05567  0.90441   
347   1   0  0.95113  0.00419  0.95183 -0.02723  0.93438 -0.01920  0.94590   
348   1   0  0.94701 -0.00034  0.93207 -0.03227  0.95177 -0.03431  0.95584   
349   1   0  0.90608 -0.01657  0.98122 -0.01989  0.95691 -0.03646  0.85746   
350   1   0  0.84710  0.13533  0.73638 -0.06151  0.87873  0.08260  0.88928   

          9   ...       24       25       26       27       28       29  \
0    0.03760  ...  0.56811 -0.51171  0.41078 -0.46168  0.21266 -0.34090   
1   -0.04549  ... -0.20332 -0.26569 -0.20468 -0.18401 -0.19040 -0.11593   
2    0.01198  ...  0.57528 -0.40220  0.58984 -0.22145  0.43100 -0.17365   
3    0.00000  ...  1.00000  0.90695  0.51613  1.00000  1.00000 -0.20099   
4   -0.16399  ...  0.03286 -0.65158  0.13290 -0.53206  0.02431 -0.62197   
..       ...  ...      ...      ...      ...      ...      ...      ...   
346 -0.04622  ...  0.95378 -0.04202  0.83479  0.00123  1.00000  0.12815   
347  0.01606  ...  0.94520  0.01361  0.93522  0.04925  0.93159  0.08168   
348  0.02446  ...  0.93988  0.03193  0.92489  0.02542  0.92120  0.02242   
349  0.00110  ...  0.91050 -0.02099  0.89147 -0.07760  0.82983 -0.17238   
350 -0.09139  ...  0.86467 -0.15114  0.81147 -0.04822  0.78207 -0.00703   

          30       31       32       33  
0    0.42267 -0.54487  0.18641 -0.45300  
1   -0.16626 -0.06288 -0.13738 -0.02447  
2    0.60436 -0.24180  0.56045 -0.38238  
3    0.25682  1.00000 -0.32382  1.00000  
4   -0.05707 -0.59573 -0.04608 -0.65697  
..       ...      ...      ...      ...  
346  0.86660 -0.10714  0.90546 -0.04307  
347  0.94066 -0.00035  0.91483  0.04712  
348  0.92459  0.00442  0.92697 -0.00577  
349  0.96022 -0.03757  0.87403 -0.16243  
350  0.75747 -0.06678  0.85764 -0.06151  

[351 rows x 34 columns]

In [25]:
# Array
array = df.values
print(array)

point1 = array[0,:]
point2 = array[1,:]
point3 = array[2,:]

[[ 1.       0.       0.99539 ... -0.54487  0.18641 -0.453  ]
 [ 1.       0.       1.      ... -0.06288 -0.13738 -0.02447]
 [ 1.       0.       1.      ... -0.2418   0.56045 -0.38238]
 ...
 [ 1.       0.       0.94701 ...  0.00442  0.92697 -0.00577]
 [ 1.       0.       0.90608 ... -0.03757  0.87403 -0.16243]
 [ 1.       0.       0.8471  ... -0.06678  0.85764 -0.06151]]


In [27]:
# P = 1
dist1_1_2 = np.linalg.norm(point1 - point2, 1)
dist1_1_3 = np.linalg.norm(point1 - point3, 1)

print('Dist 1 of point1 and point2: ', dist1_1_2)
print('Dist 1 of point1 and point3: ', dist1_1_3)

Dist 1 of point1 and point2:  13.080950000000001
Dist 1 of point1 and point3:  5.359709999999999


In [28]:
# P = 2
dist2_1_2 = np.linalg.norm(point1 - point2)
dist2_1_3 = np.linalg.norm(point1 - point3)

print('Dist 2 of point1 and point2: ', dist2_1_2)
print('Dist 2 of point1 and point3: ', dist2_1_3)

Dist 2 of point1 and point2:  2.7763589251571923
Dist 2 of point1 and point3:  1.1697276018372824


In [29]:
# P = inf
distInf_1_2 = np.linalg.norm(point1 - point2, np.inf)
distInf_1_3 = np.linalg.norm(point1 - point3, np.inf)

print('Dist 2 of point1 and point2: ', distInf_1_2)
print('Dist 2 of point1 and point3: ', distInf_1_3)

Dist 2 of point1 and point2:  1.12221
Dist 2 of point1 and point3:  0.45772


## 2. Độ đo tương đồng giữa các điểm trong tập dữ liệu categorical

In [31]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("kddcup.data\\kddcup.data.corrected", header = None)

display(df.head())

0    1     2   3    4      5   6   7   8   9   ...  32   33   34    35  \
0   0  tcp  http  SF  215  45076   0   0   0   0  ...   0  0.0  0.0  0.00   
1   0  tcp  http  SF  162   4528   0   0   0   0  ...   1  1.0  0.0  1.00   
2   0  tcp  http  SF  236   1228   0   0   0   0  ...   2  1.0  0.0  0.50   
3   0  tcp  http  SF  233   2032   0   0   0   0  ...   3  1.0  0.0  0.33   
4   0  tcp  http  SF  239    486   0   0   0   0  ...   4  1.0  0.0  0.25   

    36   37   38   39   40       41  
0  0.0  0.0  0.0  0.0  0.0  normal.  
1  0.0  0.0  0.0  0.0  0.0  normal.  
2  0.0  0.0  0.0  0.0  0.0  normal.  
3  0.0  0.0  0.0  0.0  0.0  normal.  
4  0.0  0.0  0.0  0.0  0.0  normal.  

[5 rows x 42 columns]

In [ ]:
df = df.drop([1,2,3,41], axis=1)

In [38]:
display(df)

0    4      5   6   7   8   9   10  11  12  ...  31   32   33   34  \
0         0  215  45076   0   0   0   0   0   1   0  ...   0    0  0.0  0.0   
1         0  162   4528   0   0   0   0   0   1   0  ...   1    1  1.0  0.0   
2         0  236   1228   0   0   0   0   0   1   0  ...   2    2  1.0  0.0   
3         0  233   2032   0   0   0   0   0   1   0  ...   3    3  1.0  0.0   
4         0  239    486   0   0   0   0   0   1   0  ...   4    4  1.0  0.0   
...      ..  ...    ...  ..  ..  ..  ..  ..  ..  ..  ...  ..  ...  ...  ...   
4898426   0  212   2288   0   0   0   0   0   1   0  ...   3  255  1.0  0.0   
4898427   0  219    236   0   0   0   0   0   1   0  ...   4  255  1.0  0.0   
4898428   0  218   3610   0   0   0   0   0   1   0  ...   5  255  1.0  0.0   
4898429   0  219   1234   0   0   0   0   0   1   0  ...   6  255  1.0  0.0   
4898430   0  219   1098   0   0   0   0   0   1   0  ...   7  255  1.0  0.0   

           35    36   37    38   39   40  
0        0.00  0.00  0.0  0.00  0.0  0.0  
1        1.00  0.00  0.0  0.00  0.0  0.0  
2        0.50  0.00  0.0  0.00  0.0  0.0  
3        0.33  0.00  0.0  0.00  0.0  0.0  
4        0.25  0.00  0.0  0.00  0.0  0.0  
...       ...   ...  ...   ...  ...  ...  
4898426  0.33  0.05  0.0  0.01  0.0  0.0  
4898427  0.25  0.05  0.0  0.01  0.0  0.0  
4898428  0.20  0.05  0.0  0.01  0.0  0.0  
4898429  0.17  0.05  0.0  0.01  0.0  0.0  
4898430  0.14  0.05  0.0  0.01  0.0  0.0  

[4898431 rows x 38 columns]

In [43]:
arr = df .values
scaler = StandardScaler()
arr_scaled = scaler.fit_transform(arr)

In [44]:
display(pd.DataFrame(arr_scaled))

0         1         2         3         4         5         6   \
0       -0.066833 -0.001720  0.068188 -0.002391 -0.015139 -0.001103 -0.026521   
1       -0.066833 -0.001777  0.005325 -0.002391 -0.015139 -0.001103 -0.026521   
2       -0.066833 -0.001698  0.000208 -0.002391 -0.015139 -0.001103 -0.026521   
3       -0.066833 -0.001701  0.001455 -0.002391 -0.015139 -0.001103 -0.026521   
4       -0.066833 -0.001695 -0.000942 -0.002391 -0.015139 -0.001103 -0.026521   
...           ...       ...       ...       ...       ...       ...       ...   
4898426 -0.066833 -0.001724  0.001852 -0.002391 -0.015139 -0.001103 -0.026521   
4898427 -0.066833 -0.001716 -0.001330 -0.002391 -0.015139 -0.001103 -0.026521   
4898428 -0.066833 -0.001717  0.003901 -0.002391 -0.015139 -0.001103 -0.026521   
4898429 -0.066833 -0.001716  0.000218 -0.002391 -0.015139 -0.001103 -0.026521   
4898430 -0.066833 -0.001716  0.000007 -0.002391 -0.015139 -0.001103 -0.026521   

               7         8         9   ...        28        29        30  \
0       -0.004391  2.442792 -0.002097  ... -3.639139 -1.786510 -1.833023   
1       -0.004391  2.442792 -0.002097  ... -3.623519 -1.777069  0.598967   
2       -0.004391  2.442792 -0.002097  ... -3.607899 -1.767627  0.598967   
3       -0.004391  2.442792 -0.002097  ... -3.592280 -1.758185  0.598967   
4       -0.004391  2.442792 -0.002097  ... -3.576660 -1.748744  0.598967   
...           ...       ...       ...  ...       ...       ...       ...   
4898426 -0.004391  2.442792 -0.002097  ... -3.592280  0.621132  0.598967   
4898427 -0.004391  2.442792 -0.002097  ... -3.576660  0.621132  0.598967   
4898428 -0.004391  2.442792 -0.002097  ... -3.561040  0.621132  0.598967   
4898429 -0.004391  2.442792 -0.002097  ... -3.545420  0.621132  0.598967   
4898430 -0.004391  2.442792 -0.002097  ... -3.529800  0.621132  0.598967   

               31        32        33        34        35        36        37  
0       -0.282939 -1.257937 -0.156668 -0.466405 -0.465454 -0.250832 -0.249632  
1       -0.282939  0.821119 -0.156668 -0.466405 -0.465454 -0.250832 -0.249632  
2       -0.282939 -0.218409 -0.156668 -0.466405 -0.465454 -0.250832 -0.249632  
3       -0.282939 -0.571848 -0.156668 -0.466405 -0.465454 -0.250832 -0.249632  
4       -0.282939 -0.738173 -0.156668 -0.466405 -0.465454 -0.250832 -0.249632  
...           ...       ...       ...       ...       ...       ...       ...  
4898426 -0.282939 -0.571848  1.055166 -0.466405 -0.439288 -0.250832 -0.249632  
4898427 -0.282939 -0.738173  1.055166 -0.466405 -0.439288 -0.250832 -0.249632  
4898428 -0.282939 -0.842126  1.055166 -0.466405 -0.439288 -0.250832 -0.249632  
4898429 -0.282939 -0.904497  1.055166 -0.466405 -0.439288 -0.250832 -0.249632  
4898430 -0.282939 -0.966869  1.055166 -0.466405 -0.439288 -0.250832 -0.249632  

[4898431 rows x 38 columns]

In [45]:
kbins = KBinsDiscretizer(n_bins= 10, encode= 'ordinal', strategy= 'uniform')
data_equi_width = kbins.fit_transform(arr_scaled)
data_categorical = pd.DataFrame(data_equi_width)
display(data_categorical)

c:\Users\theda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_discretization.py:248: FutureWarning: In version 1.5 onwards, subsample=200_000 will be used by default. Set subsample explicitly to silence this warning in the mean time. Set subsample=None to disable subsampling explicitly.
  warnings.warn(
c:\Users\theda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_discretization.py:278: UserWarning: Feature 16 is constant and will be replaced with 0.
  warnings.warn(


0    1    2    3    4    5    6    7    8    9   ...   28   29   30  \
0        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  0.0  0.0   
1        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  0.0  9.0   
2        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  0.0  9.0   
3        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  0.0  9.0   
4        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  0.0  9.0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
4898426  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  9.0  9.0   
4898427  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  9.0  9.0   
4898428  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  9.0  9.0   
4898429  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  9.0  9.0   
4898430  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  0.0  ...  0.0  9.0  9.0   

          31   32   33   34   35   36   37  
0        0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1        0.0  9.0  0.0  0.0  0.0  0.0  0.0  
2        0.0  4.0  0.0  0.0  0.0  0.0  0.0  
3        0.0  3.0  0.0  0.0  0.0  0.0  0.0  
4        0.0  2.0  0.0  0.0  0.0  0.0  0.0  
...      ...  ...  ...  ...  ...  ...  ...  
4898426  0.0  3.0  0.0  0.0  0.0  0.0  0.0  
4898427  0.0  2.0  0.0  0.0  0.0  0.0  0.0  
4898428  0.0  1.0  0.0  0.0  0.0  0.0  0.0  
4898429  0.0  1.0  0.0  0.0  0.0  0.0  0.0  
4898430  0.0  1.0  0.0  0.0  0.0  0.0  0.0  

[4898431 rows x 38 columns]

## 3. Yêu cầu:

In [57]:
dist1 = np.zeros((50,50))

for i in range(50):
    for j in range(50):
        dist1[i,j] = np.linalg.norm(array[i] - array[j], 1)

display(dist1)

array([[ 0.     , 13.08095,  5.35971, ..., 15.98462,  7.74504, 21.06072],
       [13.08095,  0.     , 15.80038, ..., 17.53049, 17.89603, 18.96035],
       [ 5.35971, 15.80038,  0.     , ..., 15.88161,  4.16871, 19.98939],
       ...,
       [15.98462, 17.53049, 15.88161, ...,  0.     , 16.76954, 19.93674],
       [ 7.74504, 17.89603,  4.16871, ..., 16.76954,  0.     , 21.72226],
       [21.06072, 18.96035, 19.98939, ..., 19.93674, 21.72226,  0.     ]])

In [58]:
dist2 = np.zeros((50,50))

for i in range(50):
    for j in range(50):
        dist2[i,j] = np.linalg.norm(array[i] - array[j])

display(dist2)

array([[0.        , 2.77635893, 1.1697276 , ..., 3.74495828, 1.59090253,
        4.40093478],
       [2.77635893, 0.        , 3.38003304, ..., 3.90492063, 3.91433755,
        3.96620878],
       [1.1697276 , 3.38003304, 0.        , ..., 3.82755203, 0.97067099,
        4.35585992],
       ...,
       [3.74495828, 3.90492063, 3.82755203, ..., 0.        , 4.15300217,
        4.81090468],
       [1.59090253, 3.91433755, 0.97067099, ..., 4.15300217, 0.        ,
        4.89191224],
       [4.40093478, 3.96620878, 4.35585992, ..., 4.81090468, 4.89191224,
        0.        ]])

In [59]:
distInf = np.zeros((50,50))

for i in range(50):
    for j in range(50):
        distInf[i,j] = np.linalg.norm(array[i] - array[j], np.inf)

display(distInf)

array([[0.     , 1.12221, 0.45772, ..., 1.85243, 0.5728 , 1.60536],
       [1.12221, 0.     , 1.10868, ..., 1.93035, 1.45054, 1.63147],
       [0.45772, 1.10868, 0.     , ..., 2.     , 0.42872, 1.54591],
       ...,
       [1.85243, 1.93035, 2.     , ..., 0.     , 1.98103, 2.     ],
       [0.5728 , 1.45054, 0.42872, ..., 1.98103, 0.     , 1.93369],
       [1.60536, 1.63147, 1.54591, ..., 2.     , 1.93369, 0.     ]])

In [62]:
from sklearn.metrics.pairwise import pairwise_distances
import numpy as np

# Chọn 100 dòng đầu tiên của array
subset_array = data_equi_width[:100]

# Tính ma trận độ đo tương đồng
distance_matrix = pairwise_distances(subset_array, metric='euclidean')

# Đối với độ đo tần suất xuất hiện ngược, bạn có thể sử dụng ma trận số lần xuất hiện của từng phần tử
# và tính độ tương đồng bằng cách lấy nghịch đảo của ma trận số lần xuất hiện
inverse_frequency_matrix = 1 / (1 + subset_array)

# Tính ma trận độ đo tương đồng
similarity_matrix = pairwise_distances(inverse_frequency_matrix, metric='euclidean')

# Lấy chỉ mục của các láng giềng gần nhất cho mỗi dòng
nearest_neighbors_index = similarity_matrix.argsort(axis=1)

# In ra chỉ mục của các láng giềng gần nhất cho 100 dòng đầu tiên
print(nearest_neighbors_index)

[[ 0 25 24 ... 62 70 69]
 [ 1  2  3 ... 30 63 62]
 [ 2  3  1 ... 30 63 62]
 ...
 [99 98 77 ... 63 62  0]
 [99 98 77 ... 63 62  0]
 [99 98 77 ... 63 62  0]]
